# Generated by Django 4.1.2 on 2022-10-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_rename_create_on_profilefeeditem_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='user_profile',
            new_name='user',
        ),
    ]
